### PR TITLE
Remove experimental from HKT

### PR DESCRIPTION
**Pull request by ShalokShalom**
This removes the notion of HKTs being experimental.

### CODE REVIEW

**Comment by eiriktsarpalis** [comment]
It's not saying that HKTs are experimental, only that the particular APIs are experimental. That being said they've been around long enough to be proven at this point. Thanks for the PR.

**Comment by ShalokShalom** [comment]
I honestly did not understand why you differanciate between HKT and their APIs

Didn't you implement HKT in this case?

**Comment by eiriktsarpalis** [comment]
Yes, but that was hardly my invention, see https://github.com/palladin/Higher. I was specifically referring to the APIs that use that particular manifestation of HKTs to fold generic programs.

**Comment by ShalokShalom** [comment]
Ah, so you simply copied and pasted their code over?

**Comment by eiriktsarpalis** [comment]
Not exactly, no.

**Comment by ShalokShalom** [comment]
Ah, I see. Thanks for your explaination. 

So, shortly: The implementation in Typeshape is a complete, valid and independently usable implementation of HKTs for fsharp, and can be used as such?

Trying to communicate that, some folks are really looking forward for that. 😄

**Comment by eiriktsarpalis** [comment]
Absolutely. 👍

**Pull request merged**
